import img_placeholder from '../images/Yamaha.jpg'
import YamahaPacifica from '../images/YamahaPacifica.jpg'
import IbanezGSA60 from '../images/IbanezGSA60.jpg'
import FenderStrato from '../images/FenderStrato.jpg'
import RolandLightweight from '../images/RolandLightweight.jpg'
import KorgMinilogueXD from '../images/KorgMinilogueXD.jpg'

export default [
    { id: 1, brand: "Yamaha", title: "A5R", category: "guitars", subCategory: "Acoustic", price: 130, img: img_placeholder, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 2, brand: "Fender", title: "Telecaster", category: "guitars", subCategory: "Electric", price: 1900, img: FenderStrato, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 3, brand: "Acoumera", title: "F381", category: "guitars", subCategory: "Acoustic", price: 90, img: img_placeholder, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 4, brand: "Yamaha", title: "Pacifica", category: "guitars", subCategory: "Electric", price: 250, img: YamahaPacifica, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 5, brand: "Ibanez", title: "GSA60", category: "guitars", subCategory: "Electric", price: 200, img: IbanezGSA60, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 6, brand: "Gibson", title: "Thunderbird", category: "guitars", subCategory: "Electric", price: 150, img: img_placeholder, description: " Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standarddummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum" },
    { id: 7, brand: "Roland", title: "Lightweight", category: "synth", price: 999.99, img: RolandLightweight, description: "Lightweight, gig-ready instrument with pro sounds, enhanced performance features, and battery-powered operation.Includes all the sounds from the popular JUNO-Di, plus newly updated acoustic and electric pianos, additional organs, and other stage essentials. Wave expansion slot enables users to download new sound waveforms, available for free at Roland’s Axial website. Sample import function for playing user WAV files on the JUNO-DS61’s keyboard. Intuitive eight-track pattern sequencer with non-stop recording for quickly developing song ideas; USB audio/MIDI and DAW Control model" },
    { id: 8, brand: "Korg", title: "Minilogue XD", category: "synth", price: 999, img: KorgMinilogueXD, description: "In addition to emphasizing the same real analog sound and joy of controlling an electronic musical instrument offered by the original minilogue, the Korg Minilogue xd newly adds a digital multi-engine, effects, a powered-up sequencer, and micro tuning functionality, further expanding the possibilities for sound design and performance potential." },
]