//CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_FROM_PRODUCT = 'ADD_TO_CART_FROM_PRODUCT'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'


//NOTIFICATIONS
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION'


//FETCHING DATA
export const FETCH_ITEMS_PENDING = 'FETCH_ITEMS_PENDING'
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS'
export const FETCH_ITEMS_ERROR = 'FETCH_ITEMS_ERROR'

export const FETCH_ITEM_BY_ID_PENDING = 'FETCH_ITEM_BY_ID_PENDING'
export const FETCH_ITEM_BY_ID_SUCCESS = 'FETCH_ITEM_BY_ID_SUCCESS'
export const FETCH_ITEM_BY_ID_ERROR = 'FETCH_ITEM_BY_ID_ERROR'

export const SEARCH_PENDING = 'SEARCH_PENDING'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR = 'SEARCH_ERROR'

export const SORT_BY = 'SORT_BY'


//AUTHORIZATION
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT = 'LOGOUT'

export const GET_TOKEN_DATA_PENDING = 'GET_TOKEN_DATA_PENDING'
export const GET_TOKEN_DATA_SUCCESS = 'GET_TOKEN_DATA_SUCCESS'